name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Hello world       # Name of step
      run: echo 'Hello world' # Command to run

    - name: Builds the C# code. 
      run: dotnet build
      # ..\project folder

    - name: Runs the C# tests.
      run: dotnet test
      # ..\project folder

    - name: Builds the TypeScript code - part 1.
      run: npm install
      working-directory: ./DotnetTemplate.Web

    - name: Builds the TypeScript code - part 2.
      run: npm run build
      working-directory: ./DotnetTemplate.Web
      
    - name: Runs the linter on the TypeScript code.
      run: npm run lint
      working-directory: ./DotnetTemplate.Web  

    - name: Runs the TypeScript tests.
      run: npm t
      working-directory: ./DotnetTemplate.Web
